/** @generated by scripts/build-gallery-manifest.mjs — ejecuta `npm run gallery:manifest` */

export default {
  "FestivalJazz": [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg"
  ],
  "IberoJoven": [
    "PHOTO-2026-02-25-18-20-52.jpg"
  ],
  "JCReyes": [
    "PHOTO-2026-02-25-18-20-54 (1).jpg",
    "PHOTO-2026-02-25-18-20-54.jpg"
  ],
  "JoaquinSabina": [
    "PHOTO-2026-02-25-18-24-13.jpg"
  ],
  "NewWave": [
    "3.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "14.jpg",
    "15.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "21.jpg"
  ],
  "Panorama": [
    "PHOTO-2026-02-25-18-20-53.jpg"
  ],
  "Quevedo": [
    "PHOTO-2026-02-25-18-20-52 (31f7cdb1-8923-4519-b130-3a36abf86c49).jpg"
  ],
  "Raphael": [
    "PHOTO-2026-02-25-18-22-21.jpg"
  ],
  "ViveLinares": [
    "1.jpg",
    "2.jpg",
    "4.jpg",
    "6.jpg",
    "7.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "17.jpg",
    "18.jpg",
    "19.jpg",
    "20.jpg",
    "21.jpg",
    "22.jpg",
    "23.jpg",
    "24.jpg",
    "25.jpg",
    "26.jpg",
    "27.jpg",
    "28.jpg",
    "29.jpg"
  ]
} as Record<string, string[]>;
