/** @generated by scripts/build-gallery-manifest.mjs — ejecuta `npm run gallery:manifest` */

export default {
  "FestivalJazz": [
    {
      "thumb": "1-thumb.webp",
      "full": "1-full.webp"
    },
    {
      "thumb": "2-thumb.webp",
      "full": "2-full.webp"
    },
    {
      "thumb": "3-thumb.webp",
      "full": "3-full.webp"
    },
    {
      "thumb": "4-thumb.webp",
      "full": "4-full.webp"
    },
    {
      "thumb": "5-thumb.webp",
      "full": "5-full.webp"
    },
    {
      "thumb": "6-thumb.webp",
      "full": "6-full.webp"
    },
    {
      "thumb": "7-thumb.webp",
      "full": "7-full.webp"
    },
    {
      "thumb": "8-thumb.webp",
      "full": "8-full.webp"
    }
  ],
  "IberoJoven": [
    {
      "thumb": "PHOTO-2026-02-25-18-20-52-thumb.webp",
      "full": "PHOTO-2026-02-25-18-20-52-full.webp"
    }
  ],
  "JCReyes": [
    {
      "thumb": "PHOTO-2026-02-25-18-20-54 (1)-thumb.webp",
      "full": "PHOTO-2026-02-25-18-20-54 (1)-full.webp"
    },
    {
      "thumb": "PHOTO-2026-02-25-18-20-54-thumb.webp",
      "full": "PHOTO-2026-02-25-18-20-54-full.webp"
    }
  ],
  "JoaquinSabina": [
    {
      "thumb": "PHOTO-2026-02-25-18-24-13-thumb.webp",
      "full": "PHOTO-2026-02-25-18-24-13-full.webp"
    }
  ],
  "NewWave": [
    {
      "thumb": "3-thumb.webp",
      "full": "3-full.webp"
    },
    {
      "thumb": "5-thumb.webp",
      "full": "5-full.webp"
    },
    {
      "thumb": "6-thumb.webp",
      "full": "6-full.webp"
    },
    {
      "thumb": "7-thumb.webp",
      "full": "7-full.webp"
    },
    {
      "thumb": "8-thumb.webp",
      "full": "8-full.webp"
    },
    {
      "thumb": "9-thumb.webp",
      "full": "9-full.webp"
    },
    {
      "thumb": "10-thumb.webp",
      "full": "10-full.webp"
    },
    {
      "thumb": "11-thumb.webp",
      "full": "11-full.webp"
    },
    {
      "thumb": "12-thumb.webp",
      "full": "12-full.webp"
    },
    {
      "thumb": "14-thumb.webp",
      "full": "14-full.webp"
    },
    {
      "thumb": "15-thumb.webp",
      "full": "15-full.webp"
    },
    {
      "thumb": "17-thumb.webp",
      "full": "17-full.webp"
    },
    {
      "thumb": "18-thumb.webp",
      "full": "18-full.webp"
    },
    {
      "thumb": "19-thumb.webp",
      "full": "19-full.webp"
    },
    {
      "thumb": "21-thumb.webp",
      "full": "21-full.webp"
    }
  ],
  "Panorama": [
    {
      "thumb": "PHOTO-2026-02-25-18-20-53-thumb.webp",
      "full": "PHOTO-2026-02-25-18-20-53-full.webp"
    }
  ],
  "Quevedo": [
    {
      "thumb": "PHOTO-2026-02-25-18-20-52 (31f7cdb1-8923-4519-b130-3a36abf86c49)-thumb.webp",
      "full": "PHOTO-2026-02-25-18-20-52 (31f7cdb1-8923-4519-b130-3a36abf86c49)-full.webp"
    }
  ],
  "Raphael": [
    {
      "thumb": "PHOTO-2026-02-25-18-22-21-thumb.webp",
      "full": "PHOTO-2026-02-25-18-22-21-full.webp"
    }
  ],
  "ViveLinares": [
    {
      "thumb": "1-thumb.webp",
      "full": "1-full.webp"
    },
    {
      "thumb": "2-thumb.webp",
      "full": "2-full.webp"
    },
    {
      "thumb": "4-thumb.webp",
      "full": "4-full.webp"
    },
    {
      "thumb": "6-thumb.webp",
      "full": "6-full.webp"
    },
    {
      "thumb": "7-thumb.webp",
      "full": "7-full.webp"
    },
    {
      "thumb": "9-thumb.webp",
      "full": "9-full.webp"
    },
    {
      "thumb": "10-thumb.webp",
      "full": "10-full.webp"
    },
    {
      "thumb": "11-thumb.webp",
      "full": "11-full.webp"
    },
    {
      "thumb": "12-thumb.webp",
      "full": "12-full.webp"
    },
    {
      "thumb": "13-thumb.webp",
      "full": "13-full.webp"
    },
    {
      "thumb": "14-thumb.webp",
      "full": "14-full.webp"
    },
    {
      "thumb": "15-thumb.webp",
      "full": "15-full.webp"
    },
    {
      "thumb": "16-thumb.webp",
      "full": "16-full.webp"
    },
    {
      "thumb": "17-thumb.webp",
      "full": "17-full.webp"
    },
    {
      "thumb": "18-thumb.webp",
      "full": "18-full.webp"
    },
    {
      "thumb": "19-thumb.webp",
      "full": "19-full.webp"
    },
    {
      "thumb": "20-thumb.webp",
      "full": "20-full.webp"
    },
    {
      "thumb": "21-thumb.webp",
      "full": "21-full.webp"
    },
    {
      "thumb": "22-thumb.webp",
      "full": "22-full.webp"
    },
    {
      "thumb": "23-thumb.webp",
      "full": "23-full.webp"
    },
    {
      "thumb": "24-thumb.webp",
      "full": "24-full.webp"
    },
    {
      "thumb": "25-thumb.webp",
      "full": "25-full.webp"
    },
    {
      "thumb": "26-thumb.webp",
      "full": "26-full.webp"
    },
    {
      "thumb": "27-thumb.webp",
      "full": "27-full.webp"
    },
    {
      "thumb": "28-thumb.webp",
      "full": "28-full.webp"
    },
    {
      "thumb": "29-thumb.webp",
      "full": "29-full.webp"
    }
  ]
} as Record<string, { thumb: string; full: string }[]>;
